"use client";

/* Generated by agent-observe-skill. Re-run skill.sh to refresh. */
import { useMemo, useState } from "react";

const data = {
  "generatedAt": "2026-06-18T03:36:38.924Z",
  "selected": "All detected agents",
  "summary": {
    "agents": 3,
    "prompts": 3,
    "tools": 4,
    "chains": 3,
    "routes": 1,
    "uiEntrypoints": 1,
    "risks": 13,
    "highRisks": 5,
    "mediumRisks": 8,
    "mcpClients": 0,
    "models": 1
  },
  "agents": [
    {
      "id": "route:chat",
      "name": "Chat",
      "source": "api-route",
      "files": [
        "app/api/chat/route.ts",
        "components/chat.tsx"
      ],
      "evidence": [
        {
          "file": "app/api/chat/route.ts",
          "line": 1,
          "kind": "route"
        },
        {
          "file": "app/api/chat/route.ts",
          "line": 21,
          "kind": "prompt"
        },
        {
          "file": "app/api/chat/route.ts",
          "line": 5,
          "kind": "tool"
        },
        {
          "file": "app/api/chat/route.ts",
          "line": 11,
          "kind": "tool"
        },
        {
          "file": "app/api/chat/route.ts",
          "line": 19,
          "kind": "chain"
        },
        {
          "file": "components/chat.tsx",
          "line": 5,
          "kind": "ui"
        }
      ],
      "counts": {
        "prompts": 1,
        "tools": 2,
        "chains": 1,
        "routes": 1,
        "uiEntrypoints": 1,
        "risks": 4
      },
      "description": "Static scan inference: Chat is detected from route POST /api/chat. It exposes POST /api/chat, has 1 client entry point, runs 1 model call (openai(\"gpt-4.1-mini\")), defines 2 tools (searchOrders, refundUser), uses 1 prompt.",
      "score": 21
    },
    {
      "id": "code:checkoutagent",
      "name": "checkoutAgent",
      "source": "code-symbol",
      "files": [
        "lib/checkout-agent.ts"
      ],
      "evidence": [
        {
          "file": "lib/checkout-agent.ts",
          "line": 18,
          "kind": "prompt"
        },
        {
          "file": "lib/checkout-agent.ts",
          "line": 16,
          "kind": "chain"
        }
      ],
      "counts": {
        "prompts": 1,
        "tools": 2,
        "chains": 1,
        "routes": 0,
        "uiEntrypoints": 0,
        "risks": 4
      },
      "description": "Static scan inference: checkoutAgent is detected from file lib/checkout-agent.ts. It runs 1 model call (openai(\"gpt-4.1-mini\")), defines 2 tools (chargeCard, done), uses 1 prompt.",
      "score": 14
    },
    {
      "id": "file:unbounded-agent",
      "name": "Unbounded Agent",
      "source": "file",
      "files": [
        "lib/unbounded-agent.ts"
      ],
      "evidence": [
        {
          "file": "lib/unbounded-agent.ts",
          "line": 7,
          "kind": "prompt"
        },
        {
          "file": "lib/unbounded-agent.ts",
          "line": 5,
          "kind": "chain"
        }
      ],
      "counts": {
        "prompts": 1,
        "tools": 0,
        "chains": 1,
        "routes": 0,
        "uiEntrypoints": 0,
        "risks": 4
      },
      "description": "Static scan inference: Unbounded Agent is detected from file lib/unbounded-agent.ts. It runs 1 model call (openai(\"gpt-4.1-mini\")), uses 1 prompt.",
      "score": 10
    }
  ],
  "prompts": [
    {
      "id": "prompt:app/api/chat/route.ts:21:system:1",
      "file": "app/api/chat/route.ts",
      "line": 21,
      "agentId": "route:chat",
      "kind": "system",
      "inline": true,
      "valueType": "inline literal",
      "preview": "You are a support agent. User said: ${body.message}",
      "text": "You are a support agent. User said: ${body.message}",
      "snippet": "    16 | \n    17 | export async function POST(req: Request) {\n    18 |   const body = await req.json();\n    19 |   const result = await streamText({\n    20 |     model: openai(\"gpt-4.1-mini\"),\n>   21 |     system: `You are a support agent. User said: ${body.message}`,\n    22 |     tools: { searchOrders, refundUser },\n    23 |     stopWhen: stepCountIs(8),\n    24 |     experimental_telemetry: {\n    25 |       isEnabled: true,\n    26 |       functionId: \"support-chat\",",
      "evidence": "'You are a support agent. User said: ${body.message}'"
    },
    {
      "id": "prompt:lib/checkout-agent.ts:18:instructions:2",
      "file": "lib/checkout-agent.ts",
      "line": 18,
      "agentId": "code:checkoutagent",
      "kind": "instructions",
      "inline": true,
      "valueType": "inline literal",
      "preview": "You are a checkout assistant.",
      "text": "You are a checkout assistant.",
      "snippet": "    13 |   inputSchema: z.object({ summary: z.string() }),\n    14 | });\n    15 | \n    16 | export const checkoutAgent = new ToolLoopAgent({\n    17 |   model: openai(\"gpt-4.1-mini\"),\n>   18 |   instructions: \"You are a checkout assistant.\",\n    19 |   tools: { chargeCard, done },\n    20 |   stopWhen: stepCountIs(5),\n    21 |   toolChoice: \"required\",\n    22 | });\n    23 | ",
      "evidence": "\"You are a checkout assistant.\""
    },
    {
      "id": "prompt:lib/unbounded-agent.ts:7:prompt:3",
      "file": "lib/unbounded-agent.ts",
      "line": 7,
      "agentId": "file:unbounded-agent",
      "kind": "prompt",
      "inline": true,
      "valueType": "inline literal",
      "preview": "Research this topic thoroughly",
      "text": "Research this topic thoroughly",
      "snippet": "     2 | import { openai } from \"@ai-sdk/openai\";\n     3 | \n     4 | export async function runUnbounded() {\n     5 |   return generateText({\n     6 |     model: openai(\"gpt-4.1-mini\"),\n>    7 |     prompt: \"Research this topic thoroughly\",\n     8 |     stopWhen: isLoopFinished(),\n     9 |   });\n    10 | }\n    11 | ",
      "evidence": "\"Research this topic thoroughly\""
    }
  ],
  "tools": [
    {
      "id": "tool:app/api/chat/route.ts:5:searchOrders",
      "file": "app/api/chat/route.ts",
      "line": 5,
      "agentId": "route:chat",
      "name": "searchOrders",
      "description": "\"Find orders by id\"",
      "descriptionFull": "\"Find orders by id\"",
      "schema": "orderId",
      "schemaFields": [
        {
          "name": "orderId",
          "type": "z.string()"
        }
      ],
      "hasInputSchema": true,
      "hasExecute": true,
      "needsApproval": false,
      "sideEffect": false,
      "evidence": "tool({ description: \"Find orders by id\", inputSchema: z.object({ orderId: z.string() }), execute: async ({ orderId }) => ({ orderId, status: \"shipped\" }), })",
      "snippet": "     1 | import { streamText, tool, stepCountIs } from \"ai\";\n     2 | import { openai } from \"@ai-sdk/openai\";\n     3 | import { z } from \"zod\";\n     4 | \n>    5 | const searchOrders = tool({\n     6 |   description: \"Find orders by id\",\n     7 |   inputSchema: z.object({ orderId: z.string() }),\n     8 |   execute: async ({ orderId }) => ({ orderId, status: \"shipped\" }),\n     9 | });\n    10 | "
    },
    {
      "id": "tool:app/api/chat/route.ts:11:refundUser",
      "file": "app/api/chat/route.ts",
      "line": 11,
      "agentId": "route:chat",
      "name": "refundUser",
      "description": "\"Refund an order\"",
      "descriptionFull": "\"Refund an order\"",
      "schema": "orderId",
      "schemaFields": [
        {
          "name": "orderId",
          "type": "z.string()"
        }
      ],
      "hasInputSchema": true,
      "hasExecute": true,
      "needsApproval": false,
      "sideEffect": true,
      "evidence": "tool({ description: \"Refund an order\", inputSchema: z.object({ orderId: z.string() }), execute: async ({ orderId }) => fetch('/api/refund', { method: \"POST\", body: orderId }), })",
      "snippet": "     6 |   description: \"Find orders by id\",\n     7 |   inputSchema: z.object({ orderId: z.string() }),\n     8 |   execute: async ({ orderId }) => ({ orderId, status: \"shipped\" }),\n     9 | });\n    10 | \n>   11 | const refundUser = tool({\n    12 |   description: \"Refund an order\",\n    13 |   inputSchema: z.object({ orderId: z.string() }),\n    14 |   execute: async ({ orderId }) => fetch(`/api/refund`, { method: \"POST\", body: orderId }),\n    15 | });\n    16 | "
    },
    {
      "id": "tool:lib/checkout-agent.ts:5:chargeCard",
      "file": "lib/checkout-agent.ts",
      "line": 5,
      "agentId": "code:checkoutagent",
      "name": "chargeCard",
      "description": "\"Charge the customer card\"",
      "descriptionFull": "\"Charge the customer card\"",
      "schema": "amount",
      "schemaFields": [
        {
          "name": "amount",
          "type": "z.number()"
        }
      ],
      "hasInputSchema": true,
      "hasExecute": true,
      "needsApproval": false,
      "sideEffect": true,
      "evidence": "tool({ description: \"Charge the customer card\", inputSchema: z.object({ amount: z.number() }), execute: async ({ amount }) => fetch(\"/api/charge\", { method: \"POST\", body: String(amount) }), })",
      "snippet": "     1 | import { ToolLoopAgent, stepCountIs, tool } from \"ai\";\n     2 | import { openai } from \"@ai-sdk/openai\";\n     3 | import { z } from \"zod\";\n     4 | \n>    5 | const chargeCard = tool({\n     6 |   description: \"Charge the customer card\",\n     7 |   inputSchema: z.object({ amount: z.number() }),\n     8 |   execute: async ({ amount }) => fetch(\"/api/charge\", { method: \"POST\", body: String(amount) }),\n     9 | });\n    10 | "
    },
    {
      "id": "tool:lib/checkout-agent.ts:11:done",
      "file": "lib/checkout-agent.ts",
      "line": 11,
      "agentId": "code:checkoutagent",
      "name": "done",
      "description": "\"Signal checkout completion\"",
      "descriptionFull": "\"Signal checkout completion\"",
      "schema": "summary",
      "schemaFields": [
        {
          "name": "summary",
          "type": "z.string()"
        }
      ],
      "hasInputSchema": true,
      "hasExecute": false,
      "needsApproval": false,
      "sideEffect": false,
      "evidence": "tool({ description: \"Signal checkout completion\", inputSchema: z.object({ summary: z.string() }), })",
      "snippet": "     6 |   description: \"Charge the customer card\",\n     7 |   inputSchema: z.object({ amount: z.number() }),\n     8 |   execute: async ({ amount }) => fetch(\"/api/charge\", { method: \"POST\", body: String(amount) }),\n     9 | });\n    10 | \n>   11 | const done = tool({\n    12 |   description: \"Signal checkout completion\",\n    13 |   inputSchema: z.object({ summary: z.string() }),\n    14 | });\n    15 | \n    16 | export const checkoutAgent = new ToolLoopAgent({"
    }
  ],
  "chains": [
    {
      "id": "chain:app/api/chat/route.ts:19:streamtext",
      "file": "app/api/chat/route.ts",
      "line": 19,
      "agentId": "route:chat",
      "type": "streamText",
      "model": "openai(\"gpt-4.1-mini\")",
      "modelFull": "openai(\"gpt-4.1-mini\")",
      "prompts": [
        "system: You are a support agent. User said: ${body.message}"
      ],
      "promptIds": [
        "prompt:app/api/chat/route.ts:21:system:1"
      ],
      "tools": [
        "searchOrders",
        "refundUser"
      ],
      "toolIds": [
        "tool:app/api/chat/route.ts:5:searchOrders",
        "tool:app/api/chat/route.ts:11:refundUser"
      ],
      "hasEval": false,
      "hasTrace": true,
      "structuredOutput": false,
      "evidence": "streamText({ model: openai(\"gpt-4.1-mini\"), system: 'You are a support agent. User said: ${body.message}', tools: { searchOrders, refundUser }, stopWhen: stepCountIs(8), experimental_telemetry: { isEnabled: true, functionId: \"support-chat\", recordInputs: true...",
      "snippet": "    14 |   execute: async ({ orderId }) => fetch(`/api/refund`, { method: \"POST\", body: orderId }),\n    15 | });\n    16 | \n    17 | export async function POST(req: Request) {\n    18 |   const body = await req.json();\n>   19 |   const result = await streamText({\n    20 |     model: openai(\"gpt-4.1-mini\"),\n    21 |     system: `You are a support agent. User said: ${body.message}`,\n    22 |     tools: { searchOrders, refundUser },\n    23 |     stopWhen: stepCountIs(8),\n    24 |     experimental_telemetry: {",
      "loop": {
        "stopWhen": "stepCountIs(8)",
        "maxSteps": "",
        "prepareStep": false,
        "onStepFinish": false,
        "toolChoice": "",
        "activeTools": "",
        "hasStopWhen": true,
        "stepCount": "8",
        "isUnbounded": false,
        "toolChoiceRequired": false
      },
      "telemetry": {
        "hasTelemetry": true,
        "isEnabled": true,
        "hasFunctionId": true,
        "recordInputsOn": true,
        "recordOutputsOn": true,
        "raw": "{ isEnabled: true, functionId: \"support-chat\", recordInputs: true, recordOutputs: true, }"
      }
    },
    {
      "id": "chain:lib/checkout-agent.ts:16:ToolLoopAgent",
      "file": "lib/checkout-agent.ts",
      "line": 16,
      "agentId": "code:checkoutagent",
      "type": "ToolLoopAgent",
      "model": "openai(\"gpt-4.1-mini\")",
      "modelFull": "openai(\"gpt-4.1-mini\")",
      "prompts": [
        "instructions: You are a checkout assistant."
      ],
      "promptIds": [
        "prompt:lib/checkout-agent.ts:18:instructions:2"
      ],
      "tools": [
        "chargeCard",
        "done"
      ],
      "toolIds": [
        "tool:lib/checkout-agent.ts:5:chargeCard",
        "tool:lib/checkout-agent.ts:11:done"
      ],
      "hasEval": false,
      "hasTrace": false,
      "evidence": "new ToolLoopAgent({ model: openai(\"gpt-4.1-mini\"), instructions: \"You are a checkout assistant.\", tools: { chargeCard, done }, stopWhen: stepCountIs(5), toolChoice: \"required\", })",
      "snippet": "    11 | const done = tool({\n    12 |   description: \"Signal checkout completion\",\n    13 |   inputSchema: z.object({ summary: z.string() }),\n    14 | });\n    15 | \n>   16 | export const checkoutAgent = new ToolLoopAgent({\n    17 |   model: openai(\"gpt-4.1-mini\"),\n    18 |   instructions: \"You are a checkout assistant.\",\n    19 |   tools: { chargeCard, done },\n    20 |   stopWhen: stepCountIs(5),\n    21 |   toolChoice: \"required\",",
      "loop": {
        "stopWhen": "stepCountIs(5)",
        "maxSteps": "",
        "prepareStep": false,
        "onStepFinish": false,
        "toolChoice": "\"required\"",
        "activeTools": "",
        "hasStopWhen": true,
        "stepCount": "5",
        "isUnbounded": false,
        "toolChoiceRequired": true
      },
      "telemetry": {
        "hasTelemetry": false,
        "isEnabled": false,
        "hasFunctionId": false,
        "recordInputsOn": false,
        "recordOutputsOn": false,
        "raw": ""
      }
    },
    {
      "id": "chain:lib/unbounded-agent.ts:5:generatetext",
      "file": "lib/unbounded-agent.ts",
      "line": 5,
      "agentId": "file:unbounded-agent",
      "type": "generateText",
      "model": "openai(\"gpt-4.1-mini\")",
      "modelFull": "openai(\"gpt-4.1-mini\")",
      "prompts": [
        "prompt: Research this topic thoroughly"
      ],
      "promptIds": [
        "prompt:lib/unbounded-agent.ts:7:prompt:3"
      ],
      "tools": [],
      "toolIds": [],
      "hasEval": false,
      "hasTrace": false,
      "structuredOutput": false,
      "evidence": "generateText({ model: openai(\"gpt-4.1-mini\"), prompt: \"Research this topic thoroughly\", stopWhen: isLoopFinished(), })",
      "snippet": "     1 | import { generateText, isLoopFinished } from \"ai\";\n     2 | import { openai } from \"@ai-sdk/openai\";\n     3 | \n     4 | export async function runUnbounded() {\n>    5 |   return generateText({\n     6 |     model: openai(\"gpt-4.1-mini\"),\n     7 |     prompt: \"Research this topic thoroughly\",\n     8 |     stopWhen: isLoopFinished(),\n     9 |   });\n    10 | }",
      "loop": {
        "stopWhen": "isLoopFinished()",
        "maxSteps": "",
        "prepareStep": false,
        "onStepFinish": false,
        "toolChoice": "",
        "activeTools": "",
        "hasStopWhen": true,
        "stepCount": "",
        "isUnbounded": true,
        "toolChoiceRequired": false
      },
      "telemetry": {
        "hasTelemetry": false,
        "isEnabled": false,
        "hasFunctionId": false,
        "recordInputsOn": false,
        "recordOutputsOn": false,
        "raw": ""
      }
    }
  ],
  "routes": [
    {
      "id": "route:app/api/chat/route.ts:1",
      "file": "app/api/chat/route.ts",
      "line": 1,
      "kind": "app-router",
      "methods": [
        "POST"
      ],
      "aiPatterns": [
        "streamText"
      ],
      "hasTrace": true,
      "snippet": ">    1 | import { streamText, tool, stepCountIs } from \"ai\";\n     2 | import { openai } from \"@ai-sdk/openai\";\n     3 | import { z } from \"zod\";\n     4 | \n     5 | const searchOrders = tool({\n     6 |   description: \"Find orders by id\",",
      "agentId": "route:chat"
    }
  ],
  "uiEntrypoints": [
    {
      "id": "ui:components/chat.tsx:5:useChat",
      "file": "components/chat.tsx",
      "line": 5,
      "hook": "useChat",
      "api": "\"/api/chat\"",
      "evidence": "useChat({ api: \"/api/chat\" })",
      "snippet": "     1 | \"use client\";\n     2 | import { useChat } from \"ai/react\";\n     3 | \n     4 | export function Chat() {\n>    5 |   return useChat({ api: \"/api/chat\" });\n     6 | }\n     7 | ",
      "agentId": "route:chat"
    }
  ],
  "risks": [
    {
      "id": "risk:app/api/chat/route.ts:21:inline-prompt:1",
      "kind": "inline-prompt",
      "severity": "medium",
      "file": "app/api/chat/route.ts",
      "line": 21,
      "message": "Prompt is inline and harder to audit, diff, reuse, or cover with evals.",
      "evidence": "You are a support agent. User said: ${body.message}",
      "evidenceFull": "You are a support agent. User said: ${body.message}",
      "fix": "// prompts/chat.ts\nexport const chatSystem = `...`;\n\n// In your streamText call:\nsystem: chatSystem,",
      "fixSnippet": "// prompts/chat.ts\nexport const chatSystem = `...`;\n\n// In your streamText call:\nsystem: chatSystem,",
      "targetId": "prompt:app/api/chat/route.ts:21:system:1",
      "agentId": "route:chat"
    },
    {
      "id": "risk:app/api/chat/route.ts:11:side-effect-without-approval:2",
      "kind": "side-effect-without-approval",
      "severity": "high",
      "file": "app/api/chat/route.ts",
      "line": 11,
      "message": "Tool refundUser performs side effects without needsApproval — add human-in-the-loop before destructive actions.",
      "evidence": "tool({ description: \"Refund an order\", inputSchema: z.object({ orderId: z.string() }), execute: async ({ orderId }) => fetch('/api/refund', { method: \"POST\", body: orderId }), })",
      "evidenceFull": "tool({ description: \"Refund an order\", inputSchema: z.object({ orderId: z.string() }), execute: async ({ orderId }) => fetch('/api/refund', { method: \"POST\", body: orderId }), })",
      "fix": "needsApproval: true, // require human approval before refundUser runs",
      "fixSnippet": "needsApproval: true, // require human approval before refundUser runs",
      "targetId": "tool:app/api/chat/route.ts:11:refundUser",
      "agentId": "route:chat"
    },
    {
      "id": "risk:app/api/chat/route.ts:19:telemetry-records-pii:3",
      "kind": "telemetry-records-pii",
      "severity": "medium",
      "file": "app/api/chat/route.ts",
      "line": 19,
      "message": "streamText records inputs/outputs while prompts appear to include user content — disable recordInputs/recordOutputs for PII.",
      "evidence": "{ isEnabled: true, functionId: \"support-chat\", recordInputs: true, recordOutputs: true, }",
      "evidenceFull": "{ isEnabled: true, functionId: \"support-chat\", recordInputs: true, recordOutputs: true, }",
      "fix": "experimental_telemetry: {\n  isEnabled: true,\n  functionId: 'chat_streamtext',\n  recordInputs: false,  // disable if prompts contain user PII\n  recordOutputs: false,\n},",
      "fixSnippet": "experimental_telemetry: {\n  isEnabled: true,\n  functionId: 'chat_streamtext',\n  recordInputs: false,  // disable if prompts contain user PII\n  recordOutputs: false,\n},",
      "targetId": "chain:app/api/chat/route.ts:19:streamtext",
      "agentId": "route:chat"
    },
    {
      "id": "risk:app/api/chat/route.ts:19:missing-eval:4",
      "kind": "missing-eval",
      "severity": "medium",
      "file": "app/api/chat/route.ts",
      "line": 19,
      "message": "streamText chain lacks nearby eval or test evidence.",
      "evidence": "streamText({ model: openai(\"gpt-4.1-mini\"), system: 'You are a support agent. User said: ${body.message}', tools: { searchOrders, refundUser }, stopWhen: stepCountIs(8), experimental_telemetry: { isEnabled: true, functi...",
      "evidenceFull": "streamText({\n    model: openai(\"gpt-4.1-mini\"),\n    system: `You are a support agent. User said: ${body.message}`,\n    tools: { searchOrders, refundUser },\n    stopWhen: stepCountIs(8),\n    experimental_telemetry: {\n      isEnabled: true,\n      functionId: \"support-chat\",\n      recordInputs: true,\n      recordOutputs: true,\n    },\n  })",
      "fix": "// vitest or promptfoo near this chain\ndescribe('Chat', () => {\n  it('handles expected tool flow', async () => {\n    const result = await streamText({ /* ... */ });\n    expect(result.text).toBeTruthy();\n  });\n});",
      "fixSnippet": "// vitest or promptfoo near this chain\ndescribe('Chat', () => {\n  it('handles expected tool flow', async () => {\n    const result = await streamText({ /* ... */ });\n    expect(result.text).toBeTruthy();\n  });\n});",
      "targetId": "chain:app/api/chat/route.ts:19:streamtext",
      "agentId": "route:chat"
    },
    {
      "id": "risk:lib/checkout-agent.ts:18:inline-prompt:5",
      "kind": "inline-prompt",
      "severity": "medium",
      "file": "lib/checkout-agent.ts",
      "line": 18,
      "message": "Prompt is inline and harder to audit, diff, reuse, or cover with evals.",
      "evidence": "You are a checkout assistant.",
      "evidenceFull": "You are a checkout assistant.",
      "fix": "// prompts/checkoutagent.ts\nexport const checkoutagentSystem = `...`;\n\n// In your streamText call:\nsystem: checkoutagentSystem,",
      "fixSnippet": "// prompts/checkoutagent.ts\nexport const checkoutagentSystem = `...`;\n\n// In your streamText call:\nsystem: checkoutagentSystem,",
      "targetId": "prompt:lib/checkout-agent.ts:18:instructions:2",
      "agentId": "code:checkoutagent"
    },
    {
      "id": "risk:lib/checkout-agent.ts:5:side-effect-without-approval:6",
      "kind": "side-effect-without-approval",
      "severity": "high",
      "file": "lib/checkout-agent.ts",
      "line": 5,
      "message": "Tool chargeCard performs side effects without needsApproval — add human-in-the-loop before destructive actions.",
      "evidence": "tool({ description: \"Charge the customer card\", inputSchema: z.object({ amount: z.number() }), execute: async ({ amount }) => fetch(\"/api/charge\", { method: \"POST\", body: String(amount) }), })",
      "evidenceFull": "tool({ description: \"Charge the customer card\", inputSchema: z.object({ amount: z.number() }), execute: async ({ amount }) => fetch(\"/api/charge\", { method: \"POST\", body: String(amount) }), })",
      "fix": "needsApproval: true, // require human approval before chargeCard runs",
      "fixSnippet": "needsApproval: true, // require human approval before chargeCard runs",
      "targetId": "tool:lib/checkout-agent.ts:5:chargeCard",
      "agentId": "code:checkoutagent"
    },
    {
      "id": "risk:lib/checkout-agent.ts:16:missing-trace:7",
      "kind": "missing-trace",
      "severity": "high",
      "file": "lib/checkout-agent.ts",
      "line": 16,
      "message": "ToolLoopAgent chain lacks trace ID, structured logging, or AI telemetry evidence.",
      "evidence": "new ToolLoopAgent({ model: openai(\"gpt-4.1-mini\"), instructions: \"You are a checkout assistant.\", tools: { chargeCard, done }, stopWhen: stepCountIs(5), toolChoice: \"required\", })",
      "evidenceFull": "new ToolLoopAgent({\n  model: openai(\"gpt-4.1-mini\"),\n  instructions: \"You are a checkout assistant.\",\n  tools: { chargeCard, done },\n  stopWhen: stepCountIs(5),\n  toolChoice: \"required\",\n})",
      "fix": "experimental_telemetry: {\n  isEnabled: true,\n  functionId: 'checkoutagent_toolloopagent',\n  metadata: { agent: 'checkoutAgent' },\n},",
      "fixSnippet": "experimental_telemetry: {\n  isEnabled: true,\n  functionId: 'checkoutagent_toolloopagent',\n  metadata: { agent: 'checkoutAgent' },\n},",
      "targetId": "chain:lib/checkout-agent.ts:16:ToolLoopAgent",
      "agentId": "code:checkoutagent"
    },
    {
      "id": "risk:lib/checkout-agent.ts:16:missing-eval:8",
      "kind": "missing-eval",
      "severity": "medium",
      "file": "lib/checkout-agent.ts",
      "line": 16,
      "message": "ToolLoopAgent chain lacks nearby eval or test evidence.",
      "evidence": "new ToolLoopAgent({ model: openai(\"gpt-4.1-mini\"), instructions: \"You are a checkout assistant.\", tools: { chargeCard, done }, stopWhen: stepCountIs(5), toolChoice: \"required\", })",
      "evidenceFull": "new ToolLoopAgent({\n  model: openai(\"gpt-4.1-mini\"),\n  instructions: \"You are a checkout assistant.\",\n  tools: { chargeCard, done },\n  stopWhen: stepCountIs(5),\n  toolChoice: \"required\",\n})",
      "fix": "// vitest or promptfoo near this chain\ndescribe('checkoutAgent', () => {\n  it('handles expected tool flow', async () => {\n    const result = await ToolLoopAgent({ /* ... */ });\n    expect(result.text).toBeTruthy();\n  });\n});",
      "fixSnippet": "// vitest or promptfoo near this chain\ndescribe('checkoutAgent', () => {\n  it('handles expected tool flow', async () => {\n    const result = await ToolLoopAgent({ /* ... */ });\n    expect(result.text).toBeTruthy();\n  });\n});",
      "targetId": "chain:lib/checkout-agent.ts:16:ToolLoopAgent",
      "agentId": "code:checkoutagent"
    },
    {
      "id": "risk:lib/unbounded-agent.ts:7:inline-prompt:9",
      "kind": "inline-prompt",
      "severity": "medium",
      "file": "lib/unbounded-agent.ts",
      "line": 7,
      "message": "Prompt is inline and harder to audit, diff, reuse, or cover with evals.",
      "evidence": "Research this topic thoroughly",
      "evidenceFull": "Research this topic thoroughly",
      "fix": "// prompts/unbounded_agent.ts\nexport const unbounded_agentSystem = `...`;\n\n// In your streamText call:\nsystem: unbounded_agentSystem,",
      "fixSnippet": "// prompts/unbounded_agent.ts\nexport const unbounded_agentSystem = `...`;\n\n// In your streamText call:\nsystem: unbounded_agentSystem,",
      "targetId": "prompt:lib/unbounded-agent.ts:7:prompt:3",
      "agentId": "file:unbounded-agent"
    },
    {
      "id": "risk:lib/unbounded-agent.ts:5:unbounded-loop:10",
      "kind": "unbounded-loop",
      "severity": "high",
      "file": "lib/unbounded-agent.ts",
      "line": 5,
      "message": "generateText uses isLoopFinished() without stepCountIs or hasToolCall bounds — unbounded loop / cost risk.",
      "evidence": "isLoopFinished()",
      "evidenceFull": "isLoopFinished()",
      "fix": "stopWhen: stepCountIs(10), // tighten for production; AI SDK default is stepCountIs(20)",
      "fixSnippet": "stopWhen: stepCountIs(10), // tighten for production; AI SDK default is stepCountIs(20)",
      "targetId": "chain:lib/unbounded-agent.ts:5:generatetext",
      "agentId": "file:unbounded-agent"
    },
    {
      "id": "risk:lib/unbounded-agent.ts:5:missing-trace:11",
      "kind": "missing-trace",
      "severity": "high",
      "file": "lib/unbounded-agent.ts",
      "line": 5,
      "message": "generateText chain lacks trace ID, structured logging, or AI telemetry evidence.",
      "evidence": "generateText({ model: openai(\"gpt-4.1-mini\"), prompt: \"Research this topic thoroughly\", stopWhen: isLoopFinished(), })",
      "evidenceFull": "generateText({\n    model: openai(\"gpt-4.1-mini\"),\n    prompt: \"Research this topic thoroughly\",\n    stopWhen: isLoopFinished(),\n  })",
      "fix": "experimental_telemetry: {\n  isEnabled: true,\n  functionId: 'unbounded_agent_generatetext',\n  metadata: { agent: 'Unbounded Agent' },\n},",
      "fixSnippet": "experimental_telemetry: {\n  isEnabled: true,\n  functionId: 'unbounded_agent_generatetext',\n  metadata: { agent: 'Unbounded Agent' },\n},",
      "targetId": "chain:lib/unbounded-agent.ts:5:generatetext",
      "agentId": "file:unbounded-agent"
    },
    {
      "id": "risk:lib/unbounded-agent.ts:5:missing-eval:12",
      "kind": "missing-eval",
      "severity": "medium",
      "file": "lib/unbounded-agent.ts",
      "line": 5,
      "message": "generateText chain lacks nearby eval or test evidence.",
      "evidence": "generateText({ model: openai(\"gpt-4.1-mini\"), prompt: \"Research this topic thoroughly\", stopWhen: isLoopFinished(), })",
      "evidenceFull": "generateText({\n    model: openai(\"gpt-4.1-mini\"),\n    prompt: \"Research this topic thoroughly\",\n    stopWhen: isLoopFinished(),\n  })",
      "fix": "// vitest or promptfoo near this chain\ndescribe('Unbounded Agent', () => {\n  it('handles expected tool flow', async () => {\n    const result = await generateText({ /* ... */ });\n    expect(result.text).toBeTruthy();\n  });\n});",
      "fixSnippet": "// vitest or promptfoo near this chain\ndescribe('Unbounded Agent', () => {\n  it('handles expected tool flow', async () => {\n    const result = await generateText({ /* ... */ });\n    expect(result.text).toBeTruthy();\n  });\n});",
      "targetId": "chain:lib/unbounded-agent.ts:5:generatetext",
      "agentId": "file:unbounded-agent"
    },
    {
      "id": "risk:app/api/chat/route.ts:19:scattered-models:13",
      "kind": "scattered-models",
      "severity": "medium",
      "file": "app/api/chat/route.ts",
      "line": 19,
      "message": "Model openai(\"gpt-4.1-mini\") is hardcoded in 3 files. Centralize model selection for easier upgrades.",
      "evidence": "openai(\"gpt-4.1-mini\")",
      "evidenceFull": "openai(\"gpt-4.1-mini\")",
      "fix": "// Centralize model selection\n// lib/models.ts\nexport const agentModels = {\n  route_chat: openai('gpt-4.1-mini'),\n};",
      "fixSnippet": "// Centralize model selection\n// lib/models.ts\nexport const agentModels = {\n  route_chat: openai('gpt-4.1-mini'),\n};",
      "targetId": "",
      "agentId": ""
    }
  ]
} as any;

const colors = { bg: "#f7f8f5", panel: "#fff", ink: "#171a16", muted: "#637063", line: "#d7ddd2", blue: "#2f80ed" };
const reportKinds = [["entrypoints", "Entry points"], ["tools", "Tool calls"], ["prompts", "Prompts"], ["chains", "Model calls"], ["routes", "Routes"]] as const;
const riskKinds = [["risks", "Risks"]] as const;

export default function AgentObserveSkillPage() {
  const [agentId, setAgentId] = useState<string>(data.agents[0]?.id || "");
  const [view, setView] = useState<string>("report");
  const [kind, setKind] = useState<string>("entrypoints");
  const agent = data.agents.find((item: any) => item.id === agentId);
  const byAgent = (items: any[]) => (items || []).filter((item: any) => item.agentId === agentId);
  const kinds = view === "risks" ? riskKinds : reportKinds;
  const promptTitle = (prompt: any) => prompt.kind === "system" || prompt.kind === "instructions" ? "System instructions are added" : prompt.kind === "messages" ? "Conversation context is added" : prompt.valueType === "reference" ? "User instructions are added from a shared reference" : prompt.valueType === "named constant" ? "User instructions are added from a named prompt" : "User instructions are added";
  const rows = useMemo(() => {
    if (kind === "entrypoints") return byAgent(data.uiEntrypoints).map((entry: any) => ({ meta: "User entry", title: "User sends a chat message", code: "What this means: this is where someone starts the AI experience.\nHow the user starts this: " + entry.hook + "\nWhere the message is sent: " + entry.api + "\nCode: " + entry.file + ":" + entry.line }));
    if (kind === "tools") return byAgent(data.tools).map((tool: any) => ({ meta: tool.sideEffect ? "Action" : "Lookup", title: tool.sideEffect ? "AI can change something outside the chat" : "AI can look up information", code: "What this means: " + (tool.sideEffect ? "the AI can call this helper to change product state, so permissions and logging matter." : "the AI can call this helper to fetch information before answering.") + "\nTool name: " + tool.name + "\nDescription: " + tool.description + "\nInput data: " + tool.schema + "\nCode: " + tool.file + ":" + tool.line }));
    if (kind === "prompts") return byAgent(data.prompts).map((prompt: any) => ({ meta: prompt.kind, title: promptTitle(prompt), code: "What this means: these instructions shape how the AI behaves before it answers.\nSource: " + prompt.file + ":" + prompt.line + "\nValue source: " + prompt.valueType + "\nPrompt text:\n" + (prompt.text || prompt.preview || "No prompt text resolved") }));
    if (kind === "chains") return byAgent(data.chains).map((chain: any) => ({ meta: chain.type, title: "AI generates a response", code: "What this means: the app asks an AI model to produce the next response.\nModel: " + chain.model + "\nTools available: " + ((chain.tools || []).join(", ") || "none") + "\nCode: " + chain.file + ":" + chain.line }));
    if (kind === "routes") return byAgent(data.routes).map((route: any) => ({ meta: route.kind, title: "App sends the message to the backend", code: "What this means: this endpoint receives the user's request and prepares the AI work.\nMethods: " + ((route.methods || []).join(", ") || "unknown") + "\nAI code found: " + ((route.aiPatterns || []).join(", ") || "none") + "\nCode: " + route.file }));
    return byAgent(data.risks).map((risk: any) => ({ meta: risk.severity + " / " + risk.kind, title: risk.message, code: risk.file + ":" + risk.line }));
  }, [agentId, kind]);
  const count = (item: string) => item === "entrypoints" ? byAgent(data.uiEntrypoints).length : (item === "routes" ? byAgent(data.routes).length : item === "tools" ? byAgent(data.tools).length : item === "prompts" ? byAgent(data.prompts).length : item === "chains" ? byAgent(data.chains).length : byAgent(data.risks).length);
  const activeLabel = kinds.find(([item]) => item === kind)?.[1] || "Details";
  return (
    <main style={{ minHeight: "100vh", background: "#fff", color: "#171717", padding: "64px 24px 96px", fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif" }}>
      <div style={{ maxWidth: 1152, margin: "0 auto", display: "grid", gap: 24 }}>
        <div><h1 style={{ margin: 0, fontSize: "clamp(2rem, 5vw, 3.25rem)", fontWeight: 700, letterSpacing: "-0.02em", lineHeight: 1.05 }}>Results</h1><p style={{ margin: "12px 0 0", color: "#737373", fontSize: 15 }}>Scope: <strong style={{ color: "#171717" }}>{data.selected}</strong> · Generated {data.generatedAt}</p></div>
        <section style={{ border: "1px solid #e5e5e5", borderRadius: 16, background: "#fff", padding: "24px 32px", boxShadow: "0 1px 2px rgba(0,0,0,0.04)" }}>
          <h2 style={{ margin: "0 0 20px", fontSize: 18, fontWeight: 600 }}>Agents</h2>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 12, justifyContent: "center" }}>{data.agents.map((item: any) => <button key={item.id} type="button" onClick={() => setAgentId(item.id)} style={{ minWidth: 150, border: "2px solid " + (item.id === agentId ? colors.blue : "#1f271d"), borderRadius: 8, background: "#fff", color: item.id === agentId ? colors.blue : colors.ink, padding: "16px 18px", cursor: "pointer", font: "inherit", fontWeight: 760 }}>{item.name}</button>)}</div>
        </section>
        <section style={{ border: "1px solid " + colors.line, borderRadius: 8, background: colors.panel, padding: 18, display: "grid", gridTemplateColumns: "minmax(260px, .95fr) minmax(300px, 1.05fr)", gap: 28 }}>
          <div><h2 style={{ color: colors.blue, textAlign: "center", fontSize: 30, margin: "0 0 10px" }}>{agent?.name || "No agent selected"}</h2><p style={{ maxWidth: 620, margin: "0 auto 22px", color: colors.muted, textAlign: "center", fontSize: 14, lineHeight: 1.45 }}>{agent?.description || "Select an agent to see its inferred purpose from static evidence."}</p><div style={{ display: "inline-flex", gap: 6, border: "1px solid " + colors.line, borderRadius: 8, padding: 4, marginBottom: 14 }}><button type="button" onClick={() => { setView("report"); setKind("entrypoints"); }} style={{ border: 0, borderRadius: 6, background: view === "report" ? colors.blue : "#fff", color: view === "report" ? "#fff" : colors.muted, padding: "8px 12px", cursor: "pointer", font: "inherit", fontWeight: 700 }}>Report</button><button type="button" onClick={() => { setView("risks"); setKind("risks"); }} style={{ border: 0, borderRadius: 6, background: view === "risks" ? colors.blue : "#fff", color: view === "risks" ? "#fff" : colors.muted, padding: "8px 12px", cursor: "pointer", font: "inherit", fontWeight: 700 }}>Risks</button></div><div style={{ display: "grid", gap: 12 }}>{kinds.map(([item, label]) => <button key={item} type="button" onClick={() => setKind(item)} style={{ width: "100%", border: "2px solid " + (item === kind ? colors.blue : "#1f271d"), borderRadius: 7, background: "#fff", color: item === kind ? colors.blue : colors.ink, padding: 18, cursor: "pointer", font: "inherit", fontWeight: 760 }}>{label}<small style={{ display: "block", marginTop: 4, color: colors.muted, fontWeight: 500 }}>{count(item)} detected</small></button>)}</div></div>
          <div><div style={{ textAlign: "center", marginBottom: 12, fontWeight: 760 }}>{activeLabel} info</div><div style={{ minHeight: 260, border: "2px solid " + colors.blue, borderRadius: 7, background: "#fff", padding: 18, display: "grid", gap: 12, alignContent: "start" }}>{rows.length ? rows.map((row: any, index: number) => <div key={index} style={{ borderTop: index ? "1px solid " + colors.line : 0, paddingTop: index ? 10 : 0 }}><span style={{ display: "block", color: colors.muted, fontSize: 11, letterSpacing: ".08em", textTransform: "uppercase" }}>{row.meta}</span><strong style={{ display: "block", marginTop: 5 }}>{row.title}</strong><code style={{ display: "block", marginTop: 6, color: colors.muted, fontSize: 12, overflowWrap: "anywhere", whiteSpace: "pre-wrap" }}>{row.code}</code></div>) : <p style={{ color: colors.muted }}>No {activeLabel.toLowerCase()} detected for this agent.</p>}</div></div>
        </section>
      </div>
    </main>
  );
}
